- hosts: frontend
  become: yes
 
  vars:
    ecr_uri: "{{ ecr_uri }}"
    region: "eu-north-1"
 
  tasks:
 
    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ region }} \
        | docker login --username AWS --password-stdin {{ ecr_uri }}
 
    - name: Pull latest image
      shell: docker pull {{ ecr_uri }}:latest
 
    - name: Stop old container
      shell: docker stop frontend || true
 
    - name: Remove old container
      shell: docker rm frontend || true
 
    - name: Run new container
      shell: docker run -d -p 80:80 --name frontend {{ ecr_uri }}:latest
 